export const initialStudents = [
  {
    id: 1,
    subject: "IELTS",
    name: "Абдуллах",
    lastName: "Каримов",
    dob: "06/12/2005",
    group: "IELTS A1",
    phone: "+998 99 310 22 10",
    days: "Каждый день",
    lessonTime: "09:00 - 10:20",
    note: "06.12 придет на консультацию",
    status: "row-warn",
  },
  {
    id: 2,
    subject: "GENERAL ENGLISH",
    name: "Абубакр",
    lastName: "Ахмедов",
    dob: "14/08/2004",
    group: "GE B2",
    phone: "+998 95 217 11 17",
    days: "Вторник, Четверг, Суббота",
    lessonTime: "10:30 - 11:50",
    note: "07.12 N-199",
    status: "row-success",
  },
  {
    id: 3,
    subject: "IELTS",
    name: "Саида",
    lastName: "Юсупова",
    dob: "21/03/2006",
    group: "IELTS B1",
    phone: "+998 33 747 36 37",
    days: "Понедельник, Среда, Пятница",
    lessonTime: "12:00 - 13:20",
    note: "05.12 нет времени",
    status: "row-normal",
  },
  {
    id: 4,
    subject: "GENERAL ENGLISH",
    name: "Муниса",
    lastName: "Рахимова",
    dob: "18/11/2007",
    group: "GE A2",
    phone: "+998 94 681 18 81",
    days: "Каждый день",
    lessonTime: "14:00 - 15:20",
    note: "Ждет группу",
    status: "row-normal",
  },
  {
    id: 5,
    subject: "GENERAL ENGLISH",
    name: "Хадича",
    lastName: "Турсунова",
    dob: "09/07/2005",
    group: "GE B1",
    phone: "+998 90 908 14 26",
    days: "Каждый день",
    lessonTime: "15:30 - 16:50",
    note: "Хочет прийти на speaking",
    status: "row-normal",
  },
  {
    id: 6,
    subject: "GENERAL ENGLISH",
    name: "Моминбек",
    lastName: "Собиров",
    dob: "27/01/2003",
    group: "GE C1",
    phone: "+998 93 514 17 18",
    days: "Каждый день",
    lessonTime: "17:00 - 18:20",
    note: "Ушел",
    status: "row-danger",
  },
];

export const initialGroups = [
  {
    id: 1,
    name: "IELTS",
    teacher: "Mr Abror",
    time: "14:30 - 15:50",
    days: "Понедельник, Среда, Пятница",
    status: "Активный",
  },
  {
    id: 2,
    name: "GENERAL ENGLISH",
    teacher: "Mr Nemat",
    time: "10:00 - 11:20",
    days: "Вторник, Четверг, Суббота",
    status: "Не активный",
  },
  {
    id: 3,
    name: "IELTS",
    teacher: "Mr Abror",
    time: "12:30 - 13:50",
    days: "Вторник, Четверг, Суббота",
    status: "Не active",
  },
  {
    id: 4,
    name: "GENERAL ENGLISH",
    teacher: "Mr Shokhrukh",
    time: "16:00 - 17:20",
    days: "Понедельник, Среда, Пятница",
    status: "Активный",
  },
  {
    id: 5,
    name: "GENERAL ENGLISH",
    teacher: "Mr Aziz",
    time: "11:30 - 12:50",
    days: "Понедельник, Среда, Пятница",
    status: "Активный",
  },
  {
    id: 6,
    name: "GENERAL ENGLISH",
    teacher: "Mr Shokhrukh",
    time: "13:00 - 14:20",
    days: "Понедельник, Среда, Пятница",
    status: "Активный",
  },
  {
    id: 7,
    name: "IELTS",
    teacher: "Mr Abror",
    time: "17:30 - 18:50",
    days: "Вторник, Четверг, Суббота",
    status: "Не активный",
  },
];